version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongo-database-container
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: playersData
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    networks:
      - app_network

  springapi:
    depends_on:
      - mongodb
    build:
      context: ./playersdata
      dockerfile: Dockerfile
    container_name: spring-api-container
    environment:
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      API_KEY: ${API_KEY}
      ALLOWED_ORIGINS_HEADERS: ${ALLOWED_ORIGINS_HEADERS}
    ports:
      - "8080:8080"
    networks:
      - app_network

  reactfrontend:
    depends_on:
      - springapi
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend-container
    environment:
      API_KEY: ${API_KEY}
    ports:
      - "5173:5173"
    networks:
      - app_network

networks:
  app_network:
    name: app_network
