version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: playersData
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - app_network
  
  springapi:
    depends_on:
      - mongodb
    build:
      context: ./playersdata
      dockerfile: Dockerfile
    container_name: spring
    environment:
      MONGODB_USER: admin
      MONGODB_PASSWORD: admin
      API_KEY: af83b1d9-42f6-437a-8c5a-91e7cf408672
    ports:
      - "8080:8080"
    networks:
      - app_network
    
    frontend:
      depends_on:
        - springapi
      build:
        context: ./frontend
        dockerfile: Dockerfile
      container_name: frontend
      environment:
        API_KEY: af83b1d9-42f6-437a-8c5a-91e7cf408672
      ports:
        - "5173:5173"
      networks:
        - app_network

networks:
  app_network:
    name: app_network
